---
- hosts: webservers 
  become: True
  tasks:
    - name: Install packages
      yum:
        name: "tomcat"
        state: "present"
    - name: Start tomcat server
      service:
        name: tomcat
        state: started
        enabled: True
    - name: Deploy static website
      copy:
        src: index.html # We have define a html page 
        dest: /var/www/html/
